<?php

declare(strict_types=1);

/** @var array<string, mixed> $solicitud */
$value = static fn (string $key): string => e((string) ($solicitud[$key] ?? ''));
$state = trim((string) ($solicitud['estado'] ?? '')) ?: 'RECIBIDA';
$stateLabel = mb_strtoupper($state, 'UTF-8');
$history = is_array($authorizationHistory ?? null) ? $authorizationHistory : [];
$latestAuthorization = $history !== [] ? $history[count($history) - 1] : null;
$hasProduct = ($solicitud['producto_id_externo'] ?? null) !== null || ($solicitud['producto_codigo'] ?? null) !== null;
$matchScore = $solicitud['match_score'] ?? null;
$matchLabel = $matchScore !== null && $matchScore !== '' ? (string) $matchScore . '%' : 'Sin dato';
?>
<div class="request-detail">
<section class="page-heading page-heading--dashboard request-detail__heading" aria-labelledby="request-title">
    <div class="page-heading__eyebrow"><p class="page-heading__path"><a href="/app#centro-notificaciones">Centro de notificaciones</a> <span aria-hidden="true">/</span> Solicitud</p><span class="status-label"><span aria-hidden="true"></span><?= e($stateLabel) ?></span></div>
    <h1 id="request-title">Solicitud de cotización</h1>
    <p class="request-detail__folio"><strong><?= $value('folio') ?></strong><span><?= $value('created_at') ?></span></p>
    <p class="page-heading__privacy">Solicitud asignada a <?= $value('vendedor') ?: 'vendedor pendiente' ?>.</p>
</section>
<div class="home-grid home-grid--secondary request-detail__grid">
    <section class="home-section" aria-labelledby="client-title"><div class="home-section__heading"><div><p class="section-kicker">Contacto</p><h2 id="client-title">Cliente</h2></div></div><dl class="context-summary request-detail__summary"><div><dt>Nombre</dt><dd><?= $value('nombre_cliente') ?></dd></div><div><dt>Teléfono</dt><dd><?= $value('telefono') ?: 'No indicado' ?></dd></div><div><dt>Correo</dt><dd><?= $value('correo') ?: 'No indicado' ?></dd></div><div><dt>Vendedor</dt><dd><?= $value('vendedor') ?: 'Pendiente' ?></dd></div></dl></section>
    <section class="home-section" aria-labelledby="request-text-title"><div class="home-section__heading"><div><p class="section-kicker">Mensaje recibido</p><h2 id="request-text-title">Solicitud</h2></div></div><p class="request-detail__message"><?= nl2br($value('solicitud')) ?></p></section>
</div>
<section class="home-section request-detail__product" aria-labelledby="product-title"><div class="home-section__heading"><div><p class="section-kicker">Resultado de búsqueda</p><h2 id="product-title">Producto sugerido</h2></div><?php if ($hasProduct): ?><span class="status-label"><span aria-hidden="true"></span><?= e($matchLabel) ?> coincidencia</span><?php endif; ?></div>
<?php if (!$hasProduct): ?><div class="empty-state" role="status"><strong>No se encontró un producto sugerido automáticamente.</strong><p>La solicitud puede revisarse manualmente.</p></div><?php else: ?><div class="request-detail__product-compact"><strong><?= $value('producto_codigo') ?: $value('producto_id_externo') ?></strong><p><?= $value('producto_descripcion') ?: 'No indicada' ?></p><span><?= $value('producto_marca') ?: 'Marca no indicada' ?> · <?= $value('producto_unidad') ?: 'Unidad no indicada' ?></span><small>Coincidencia: <?= $value('match_motivo') ?: 'No indicada' ?></small></div><?php endif; ?></section>
<?php $quote = is_array($quote ?? null) ? $quote : null; $query = []; parse_str((string) (parse_url((string) ($_SERVER['REQUEST_URI'] ?? ''), PHP_URL_QUERY) ?? ''), $query); $policyError = (string) ($query['error'] ?? ''); $priceState = 'SIN PRECIO PROPUESTO'; $priceStateClass = 'neutral'; if ($quote) { $sale = $quote['precio_venta'] === null ? null : (float) $quote['precio_venta']; $latestState = strtoupper((string) ($latestAuthorization['estado'] ?? '')); if ($sale === null) { $priceState = 'SIN PRECIO PROPUESTO'; } elseif ($quote['estado_precio'] === 'BLOQUEADO') { $priceState = 'FUERA DE POLÍTICA'; $priceStateClass = 'danger'; } elseif ($latestState === 'PENDIENTE') { $priceState = 'AUTORIZACIÓN PENDIENTE'; $priceStateClass = 'warning'; } elseif ($latestState === 'APROBADA' || $quote['estado_precio'] === 'APROBADO') { $priceState = 'PRECIO AUTORIZADO'; $priceStateClass = 'success'; } elseif ($latestState === 'RECHAZADA' || $quote['estado_precio'] === 'RECHAZADO') { $priceState = 'PRECIO RECHAZADO'; $priceStateClass = 'danger'; } elseif ($quote['estado_precio'] === 'REQUIERE_AUTORIZACION') { $priceState = 'REQUIERE AUTORIZACIÓN'; $priceStateClass = 'warning'; } elseif ($quote['estado_precio'] === 'PERMITIDO') { $priceState = 'PRECIO PERMITIDO'; $priceStateClass = 'success'; } } ?>
<section class="home-section request-detail__quote" aria-labelledby="quote-title"><div class="home-section__heading"><div><p class="section-kicker">Preparar cotización</p><h2 id="quote-title">Cotización</h2></div><span class="request-detail__state request-detail__state--<?= e($priceStateClass) ?>" role="status"><?= e($priceState) ?></span></div>
<?php if ($policyError === 'policy'): ?><p class="request-detail__policy-error" role="alert">⛔ El precio solicitado está fuera de la política permitida.</p><?php endif; ?>
<?php if (!$quote): ?><p>No hay precio vigente inequívoco para preparar esta solicitud.</p><?php else: $base=(float)$quote['precio_base'];$sale=$quote['precio_venta']===null?null:(float)$quote['precio_venta'];$diff=$sale===null?null:$sale-$base;$pct=$sale===null||$base==0?null:(($sale-$base)/$base*100);$showReason=in_array($priceState,['REQUIERE AUTORIZACIÓN','AUTORIZACIÓN PENDIENTE'],true); ?><div class="request-detail__price-public"><span>Precio Público</span><strong><?= e(number_format($base,2,'.',',')) ?> <?= e((string)$quote['moneda_codigo']) ?></strong></div><?php if($sale!==null): ?><div class="request-detail__proposed-summary"><span>Precio propuesto: <strong><?= e(number_format($sale,2,'.',',')) ?> <?= e((string)$quote['moneda_codigo']) ?></strong></span><span>Diferencia: <strong><?= e(number_format($diff,2,'.',',')) ?> (<?= e(number_format($pct,2,'.',',')) ?>%)</strong></span></div><?php endif; ?><?php if($priceState !== 'PRECIO AUTORIZADO'): ?><form method="post" action="/app/solicitudes-cotizacion/<?= (int)$solicitud['id'] ?>/precio" class="request-detail__price-form"><?= csrf_field($csrf) ?><label>Cantidad<input type="number" name="cantidad" min="1" step="1" value="<?= e((string)($quote['cantidad'] ?: 1)) ?>"></label><label>Precio de venta<input required type="number" name="precio_venta" min="0" step="0.01" value="<?= $sale===null?'':e((string)$quote['precio_venta']) ?>"></label><?php if($showReason): ?><label class="request-detail__reason">Motivo (obligatorio)<textarea name="motivo" rows="3" required></textarea></label><?php endif; ?><button class="button button--primary" type="submit"><?= $priceState === 'REQUIERE AUTORIZACIÓN' ? 'Solicitar autorización' : 'Guardar y continuar' ?></button></form><?php endif; ?><?php endif; ?></section>
<?php if ($history !== []): ?><section class="home-section request-detail__history" aria-labelledby="authorization-history"><div class="home-section__heading"><h2 id="authorization-history">Historial de autorizaciones</h2></div><div class="request-detail__history-list"><?php foreach($history as $h): ?><article><time><?= e((string)$h['solicitado_at']) ?></time><strong><?= e(number_format((float)$h['precio_solicitado'],2,'.',',')) ?> <?= e((string)($quote['moneda_codigo'] ?? '')) ?></strong><span><?= e((string)$h['estado']) ?></span><p><?= e((string)$h['motivo']) ?></p><?php if($h['decidido_por']): ?><small>Decidió usuario #<?= (int)$h['decidido_por'] ?> el <?= e((string)$h['decidido_at']) ?></small><?php endif; ?></article><?php endforeach; ?></div></section><?php endif; ?>
<?php if ($quote && ($quote['estado'] ?? '') === 'LISTA'): ?><section class="home-section request-detail__quote" aria-labelledby="commercial-title"><div class="home-section__heading"><h2 id="commercial-title">Cotización comercial</h2><span class="status-label"><span aria-hidden="true"></span>Vista previa</span></div><form method="post" action="/app/solicitudes-cotizacion/<?= (int)$solicitud['id'] ?>/comercial" class="form-stack"><?= csrf_field($csrf) ?><label>Empresa emisora<select name="empresa_id" required><?php if (!empty($activeCompany)): ?><option value="<?= (int)$activeCompany['id'] ?>"><?= e((string)$activeCompany['name']) ?></option><?php endif; ?></select></label><label>Impuesto<select name="impuesto_id" required><option value="">Selecciona un impuesto</option><?php foreach (($taxes ?? []) as $tax): ?><option value="<?= (int)$tax['id'] ?>"><?= e((string)$tax['nombre']) ?> (<?= e((string)((float)$tax['tasa'] * 100)) ?>%)</option><?php endforeach; ?></select></label><label>Vigencia (días)<input type="number" name="vigencia_dias" min="1" required></label><label>Condiciones de pago<input type="text" name="condiciones_pago" required maxlength="255"></label><label>Observaciones<textarea name="observaciones" rows="3"></textarea></label><button class="button button--primary" type="submit">Guardar vista previa</button></form><?php if (!empty($quote['subtotal'])): ?><dl class="request-detail__price-summary"><div><dt>Subtotal</dt><dd><?= e((string)$quote['subtotal']) ?></dd></div><div><dt>Impuesto</dt><dd><?= e((string)$quote['impuesto_importe']) ?></dd></div><div><dt>Total</dt><dd><?= e((string)$quote['total']) ?></dd></div></dl><form method="post" action="/app/solicitudes-cotizacion/<?= (int)$solicitud['id'] ?>/emitir"><?= csrf_field($csrf) ?><button class="button button--primary" type="submit">Emitir cotización</button></form><?php endif; ?></section><?php endif; ?>
</div>
