<?php
declare(strict_types=1);
namespace App\Infrastructure\Repositories;
use App\Infrastructure\Database\ConnectionProvider;
use PDO;
final class LegacyQuotationRepository
{
 public function __construct(private readonly ConnectionProvider $connection){}
 public function resolvePrice(string $code):array{ $q=$this->connection->pdo()->prepare("SELECT p.id AS producto_id,p.descripcion,p.id_producto,pub.id AS precio_publico_id,minp.id AS precio_minimo_id,pub.lista_precio_id AS lista_publico_id,minp.lista_precio_id AS lista_minimo_id,pub.moneda_id,pub.precio AS precio_base,minp.precio AS precio_minimo,m.codigo AS moneda_codigo FROM productos p JOIN precios_productos pub ON pub.producto_id=p.id JOIN listas_precios lp_pub ON lp_pub.id=pub.lista_precio_id AND lp_pub.codigo='1' AND lp_pub.activo=1 AND lp_pub.deleted_at IS NULL JOIN precios_productos minp ON minp.producto_id=p.id JOIN listas_precios lp_min ON lp_min.id=minp.lista_precio_id AND lp_min.codigo='2' AND lp_min.activo=1 AND lp_min.deleted_at IS NULL JOIN monedas m ON m.id=pub.moneda_id WHERE p.id_producto=:code AND p.activo=1 AND p.deleted_at IS NULL AND pub.activo=1 AND pub.deleted_at IS NULL AND minp.activo=1 AND minp.deleted_at IS NULL AND pub.moneda_id=minp.moneda_id");$q->execute(['code'=>$code]);$r=$q->fetchAll(PDO::FETCH_ASSOC);if(count($r)!==1||((float)$r[0]['precio_minimo']>(float)$r[0]['precio_base']))throw new \RuntimeException('Configuración de precios inválida o ambigua.');return $r[0]; }
 public function findDraft(int $sid,int $uid):?array{$q=$this->connection->pdo()->prepare("SELECT c.*,cp.*,m.codigo AS moneda_codigo,(SELECT estado FROM autorizaciones_precio_cotizacion a WHERE a.cotizacion_partida_id=cp.id ORDER BY a.id DESC LIMIT 1) authorization_status FROM cotizaciones c JOIN cotizacion_partidas cp ON cp.cotizacion_id=c.id JOIN monedas m ON m.id=cp.moneda_id WHERE c.solicitud_cotizacion_id=:s AND c.vendedor_usuario_id=:u LIMIT 1");$q->execute(['s'=>$sid,'u'=>$uid]);$r=$q->fetch(PDO::FETCH_ASSOC);return $r?:null;}
 public function createDraft(int $sid,int $uid,array $p):array{$db=$this->connection->pdo();$db->beginTransaction();try{$q=$db->prepare("INSERT INTO cotizaciones(solicitud_cotizacion_id,vendedor_usuario_id,estado) VALUES(:s,:u,'BORRADOR')");$q->execute(['s'=>$sid,'u'=>$uid]);$cid=(int)$db->lastInsertId();$q=$db->prepare('INSERT INTO cotizacion_partidas(cotizacion_id,producto_id,precio_publico_origen_id,precio_minimo_origen_id,lista_precio_publico_id,lista_precio_minimo_id,moneda_id,descripcion_snapshot,precio_base,precio_minimo) VALUES(:c,:p,:pp,:pm,:lp,:lm,:m,:d,:b,:n)');$q->execute(['c'=>$cid,'p'=>$p['producto_id'],'pp'=>$p['precio_publico_id'],'pm'=>$p['precio_minimo_id'],'lp'=>$p['lista_publico_id'],'lm'=>$p['lista_minimo_id'],'m'=>$p['moneda_id'],'d'=>$p['descripcion'],'b'=>$p['precio_base'],'n'=>$p['precio_minimo']]);$db->commit();return $this->findDraft($sid,$uid)??[];}catch(\Throwable $e){if($db->inTransaction())$db->rollBack();throw $e;}}
 public function setPrice(int $cid,int $uid,string $price,?string $reason,?string $quantity=null):array{$db=$this->connection->pdo();$db->beginTransaction();try{$q=$db->prepare('SELECT c.id,cp.id partida_id,cp.producto_id,cp.precio_base,cp.precio_minimo,cp.moneda_id,cp.cantidad FROM cotizaciones c JOIN cotizacion_partidas cp ON cp.cotizacion_id=c.id WHERE c.id=:c AND c.vendedor_usuario_id=:u FOR UPDATE');$q->execute(['c'=>$cid,'u'=>$uid]);$r=$q->fetch(PDO::FETCH_ASSOC);if(!$r)throw new \RuntimeException('Cotización no disponible.');$v=(float)$price;$b=(float)$r['precio_base'];$n=(float)$r['precio_minimo'];if($v<$n)throw new \RuntimeException('El precio es inferior al mínimo permitido.');$state=$v>=$b?'PERMITIDO':'REQUIERE_AUTORIZACION';if($state!=='PERMITIDO'&&trim((string)$reason)==='')throw new \RuntimeException('El motivo es obligatorio.');$db->prepare("UPDATE autorizaciones_precio_cotizacion SET estado='CANCELADA',decidido_at=NOW() WHERE cotizacion_partida_id=:p AND estado='PENDIENTE' AND precio_solicitado<>:v")->execute(['p'=>$r['partida_id'],'v'=>$v]);$db->prepare('UPDATE cotizacion_partidas SET cantidad=:q,precio_venta=:v,estado_precio=:e,updated_at=NOW() WHERE id=:p')->execute(['q'=>max(1,(float)($quantity??$r['cantidad'])),'v'=>$v,'e'=>$state,'p'=>$r['partida_id']]);$db->prepare('UPDATE cotizaciones SET estado=:s,updated_at=NOW() WHERE id=:c')->execute(['s'=>$state==='PERMITIDO'?'LISTA':'PENDIENTE_AUTORIZACION','c'=>$cid]);if($state!=='PERMITIDO'){$x=$db->prepare("SELECT id FROM autorizaciones_precio_cotizacion WHERE cotizacion_partida_id=:p AND precio_solicitado=:v AND estado='PENDIENTE'");$x->execute(['p'=>$r['partida_id'],'v'=>$v]);if(!$x->fetchColumn())$db->prepare('INSERT INTO autorizaciones_precio_cotizacion(cotizacion_id,cotizacion_partida_id,producto_id,solicitado_por,precio_base_referencia,precio_minimo_referencia,precio_solicitado,cantidad,moneda_id,motivo) VALUES(:c,:p,:prod,:u,:b,:n,:v,:q,:m,:r)')->execute(['c'=>$cid,'p'=>$r['partida_id'],'prod'=>$r['producto_id'],'u'=>$uid,'b'=>$b,'n'=>$n,'v'=>$v,'q'=>$r['cantidad'],'m'=>$r['moneda_id'],'r'=>trim((string)$reason)]);}$db->commit();return ['estado_precio'=>$state,'precio_venta'=>$v];}catch(\Throwable $e){if($db->inTransaction())$db->rollBack();throw $e;}}
 public function pendingAuthorizations():array{$q=$this->connection->pdo()->query("SELECT a.*,c.solicitud_cotizacion_id,s.folio,s.nombre_cliente,s.vendedor,cp.descripcion_snapshot,u.nombre solicitante_nombre FROM autorizaciones_precio_cotizacion a JOIN cotizaciones c ON c.id=a.cotizacion_id JOIN solicitudes_cotizacion s ON s.id=c.solicitud_cotizacion_id JOIN cotizacion_partidas cp ON cp.id=a.cotizacion_partida_id JOIN usuarios u ON u.id=a.solicitado_por WHERE a.estado='PENDIENTE' ORDER BY a.solicitado_at");return $q->fetchAll(PDO::FETCH_ASSOC);}
 public function authorizerRecipients():array{$q=$this->connection->pdo()->query("SELECT DISTINCT u.id,u.nombre,u.nombre_2,u.apellido_paterno,u.apellido_materno,r.codigo rol_codigo FROM usuarios u JOIN usuario_rol ur ON ur.usuario_id=u.id JOIN roles r ON r.id=ur.rol_id JOIN rol_permiso rp ON rp.rol_id=r.id JOIN permisos p ON p.id=rp.permiso_id WHERE u.activo=1 AND u.deleted_at IS NULL AND r.activo=1 AND p.codigo='precios.autorizaciones.aprobar'");return $q->fetchAll(PDO::FETCH_ASSOC);}
 public function roleCodeForUser(int $uid):?string{$q=$this->connection->pdo()->prepare("SELECT r.codigo FROM usuario_rol ur JOIN roles r ON r.id=ur.rol_id WHERE ur.usuario_id=:u AND r.activo=1 ORDER BY CASE r.codigo WHEN 'VENTAS' THEN 1 WHEN 'ADMIN' THEN 2 WHEN 'GERENCIA' THEN 3 ELSE 9 END LIMIT 1");$q->execute(['u'=>$uid]);$r=$q->fetchColumn();return $r===false?null:(string)$r;}
 public function authorizationHistory(int $sid,int $uid):array{$q=$this->connection->pdo()->prepare("SELECT a.*,c.solicitud_cotizacion_id FROM autorizaciones_precio_cotizacion a JOIN cotizaciones c ON c.id=a.cotizacion_id WHERE c.solicitud_cotizacion_id=:s AND c.vendedor_usuario_id=:u ORDER BY a.solicitado_at ASC,a.id ASC");$q->execute(['s'=>$sid,'u'=>$uid]);return $q->fetchAll(PDO::FETCH_ASSOC);}
 public function authorizationContext(int $aid):?array{$q=$this->connection->pdo()->prepare("SELECT a.*,s.folio,s.nombre_cliente,s.vendedor FROM autorizaciones_precio_cotizacion a JOIN cotizaciones c ON c.id=a.cotizacion_id JOIN solicitudes_cotizacion s ON s.id=c.solicitud_cotizacion_id WHERE a.id=:id");$q->execute(['id'=>$aid]);$r=$q->fetch(PDO::FETCH_ASSOC);return $r?:null;}
 public function decideAuthorization(int $aid,int $uid,bool $approve):void{$db=$this->connection->pdo();$db->beginTransaction();try{$q=$db->prepare('SELECT * FROM autorizaciones_precio_cotizacion WHERE id=:id FOR UPDATE');$q->execute(['id'=>$aid]);$a=$q->fetch(PDO::FETCH_ASSOC);if(!$a||$a['estado']!=='PENDIENTE')throw new \RuntimeException('La autorización ya no está pendiente.');if((int)$a['solicitado_por']===$uid)throw new \RuntimeException('No puedes aprobar tu propia solicitud.');$e=$approve?'APROBADA':'RECHAZADA';$db->prepare('UPDATE autorizaciones_precio_cotizacion SET estado=:e,decidido_por=:u,decidido_at=NOW() WHERE id=:id')->execute(['e'=>$e,'u'=>$uid,'id'=>$aid]);$db->prepare('UPDATE cotizacion_partidas SET estado_precio=:e WHERE id=:p')->execute(['e'=>$approve?'APROBADO':'RECHAZADO','p'=>$a['cotizacion_partida_id']]);$db->prepare('UPDATE cotizaciones SET estado=:e,updated_at=NOW() WHERE id=:c')->execute(['e'=>$approve?'LISTA':'BORRADOR','c'=>$a['cotizacion_id']]);$db->commit();}catch(\Throwable $e){if($db->inTransaction())$db->rollBack();throw $e;}}
 public function taxes():array{return $this->connection->pdo()->query("SELECT id,codigo,nombre,tasa,incluido_en_precio FROM impuestos WHERE activo=1 AND deleted_at IS NULL AND codigo IN ('IVA16','IVA0','EXENTO') ORDER BY id")->fetchAll(PDO::FETCH_ASSOC);}
 public function saveCommercial(int $cid,int $uid,array $d):array{$db=$this->connection->pdo();$db->beginTransaction();try{$q=$db->prepare('SELECT c.*,cp.moneda_id,cp.precio_venta,cp.cantidad,cp.estado_precio FROM cotizaciones c JOIN cotizacion_partidas cp ON cp.cotizacion_id=c.id WHERE c.id=:c AND c.vendedor_usuario_id=:u FOR UPDATE');$q->execute(['c'=>$cid,'u'=>$uid]);$r=$q->fetch(PDO::FETCH_ASSOC);if(!$r)throw new \RuntimeException('Cotización no disponible.');if(!in_array($r['estado'],['LISTA','BORRADOR'],true)||in_array($r['estado_precio'],['BLOQUEADO','REQUIERE_AUTORIZACION'],true))throw new \RuntimeException('La cotización no está lista.');$e=$db->prepare('SELECT id,razon_social,rfc,direccion FROM empresas WHERE id=:id AND activo=1 AND deleted_at IS NULL');$e->execute(['id'=>(int)$d['empresa_id']]);$company=$e->fetch(PDO::FETCH_ASSOC);if(!$company)throw new \RuntimeException('Empresa emisora inválida.');$t=$db->prepare('SELECT id,codigo,tasa FROM impuestos WHERE id=:id AND activo=1 AND deleted_at IS NULL');$t->execute(['id'=>(int)$d['impuesto_id']]);$tax=$t->fetch(PDO::FETCH_ASSOC);if(!$tax)throw new \RuntimeException('Impuesto inválido.');$days=(int)$d['vigencia_dias'];if($days<1||trim((string)$d['condiciones_pago'])==='')throw new \RuntimeException('Vigencia y condiciones de pago son obligatorias.');$subtotal=round((float)$r['precio_venta']*(float)$r['cantidad'],6);$taxAmount=round($subtotal*(float)$tax['tasa'],6);$total=$subtotal+$taxAmount;$db->prepare('UPDATE cotizaciones SET empresa_id=:e,empresa_razon_social_snapshot=:rs,empresa_rfc_snapshot=:rfc,empresa_direccion_snapshot=:dir,cliente_nombre_snapshot=(SELECT nombre_cliente FROM solicitudes_cotizacion s WHERE s.id=cotizaciones.solicitud_cotizacion_id),cliente_telefono_snapshot=(SELECT telefono FROM solicitudes_cotizacion s WHERE s.id=cotizaciones.solicitud_cotizacion_id),cliente_correo_snapshot=(SELECT correo FROM solicitudes_cotizacion s WHERE s.id=cotizaciones.solicitud_cotizacion_id),moneda_id_snapshot=:m,moneda_codigo_snapshot=(SELECT codigo FROM monedas WHERE id=:m),impuesto_id=:ti,impuesto_codigo_snapshot=:tc,impuesto_tasa_snapshot=:tt,vigencia_dias=:v,condiciones_pago=:cp,observaciones=:o,subtotal=:sub,impuesto_importe=:imp,total=:tot,updated_at=NOW() WHERE id=:c')->execute(['e'=>$company['id'],'rs'=>$company['razon_social'],'rfc'=>$company['rfc'],'dir'=>$company['direccion'],'m'=>$r['moneda_id'],'ti'=>$tax['id'],'tc'=>$tax['codigo'],'tt'=>$tax['tasa'],'v'=>$days,'cp'=>trim((string)$d['condiciones_pago']),'o'=>trim((string)($d['observaciones']??'')),'sub'=>$subtotal,'imp'=>$taxAmount,'tot'=>$total,'c'=>$cid]);$db->prepare('UPDATE cotizacion_partidas SET precio_unitario_snapshot=precio_venta,importe_snapshot=precio_venta*cantidad WHERE cotizacion_id=:c')->execute(['c'=>$cid]);$db->commit();return ['subtotal'=>$subtotal,'impuesto'=>$taxAmount,'total'=>$total];}catch(\Throwable $e){if($db->inTransaction())$db->rollBack();throw $e;}}
 public function emit(int $cid,int $uid):array{$db=$this->connection->pdo();$db->beginTransaction();try{$q=$db->prepare("SELECT * FROM cotizaciones WHERE id=:c AND vendedor_usuario_id=:u FOR UPDATE");$q->execute(['c'=>$cid,'u'=>$uid]);$r=$q->fetch(PDO::FETCH_ASSOC);if(!$r||$r['estado']!=='LISTA')throw new \RuntimeException('La cotización debe estar LISTA.');foreach(['empresa_id','impuesto_id','moneda_id_snapshot','vigencia_dias','condiciones_pago','subtotal','total'] as $k)if($r[$k]===null||$r[$k]==='')throw new \RuntimeException('Faltan datos comerciales.');$folio=$r['folio_comercial']?:('COT-'.date('Y').'-'.str_pad((string)$cid,6,'0',STR_PAD_LEFT));$db->prepare("UPDATE cotizaciones SET folio_comercial=:f,estado='EMITIDA',emitida_at=NOW(),updated_at=NOW() WHERE id=:c")->execute(['f'=>$folio,'c'=>$cid]);$db->commit();return ['folio'=>$folio,'subtotal'=>$r['subtotal'],'impuesto'=>$r['impuesto_importe'],'total'=>$r['total']];}catch(\Throwable $e){if($db->inTransaction())$db->rollBack();throw $e;}}
}





